alias us='setxkbmap us'
alias fr='setxkbmap fr'
alias la='ls -la'
alias l='ls'
alias ll='ls -l'
alias ..='cd ..'
alias ...='cd ../..'
alias gadd='git add -Av'
alias gcommit='git commit -m '
alias gpush='git push -v origin master'
alias gend='git add -Av && git commit -m "end of day push" && git push -v origin master'
alias gpull='git pull -v '

git='http://github.com/'
gqwaz=$git'qwazerty/'
