#!/bin/sh

#################################
# dotmybashrc config file       #
# by Kevin "qwazerty" Houdebert #
# houdeb_k / EPITA 2015         #
#################################

# Load all files in ~/.zsh/
for file in ~/.zsh/*; do
    source $file
done
