#!/bin/sh

#################################
# dotmybashrc config file       #
# by Kevin "qwazerty" Houdebert #
#################################

# Load all files in ~/.zsh/
for file in ~/.zsh/*.zsh; do
    source $file
done
